import { NextRequest,NextResponse } from 'next/server'
import { z } from 'zod'
import { apiUser } from '@/lib/api-auth'
import { prisma } from '@/lib/prisma'
import { sameOrigin } from '@/lib/security'
const hhmm=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/)
const patch=z.object({name:z.string().trim().min(1).max(120).optional(),emoji:z.string().max(12).optional(),targetPerWeek:z.number().int().min(1).max(7).optional(),targetPerDay:z.number().int().min(1).max(50).optional(),reminderMode:z.enum(['NONE','FIXED','INTERVAL']).optional(),reminderTime:hhmm.nullable().optional(),reminderIntervalMinutes:z.number().int().min(15).max(1440).nullable().optional(),reminderStartTime:hhmm.nullable().optional(),reminderEndTime:hhmm.nullable().optional()})
type Params={params:Promise<{id:string}>}
export async function PATCH(req:NextRequest,ctx:Params){const user=await apiUser(req);if(!user)return NextResponse.json({error:'UNAUTHORIZED'},{status:401});if(!sameOrigin(req))return NextResponse.json({error:'Invalid origin'},{status:403});const {id}=await ctx.params;const parsed=patch.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'INVALID_DATA'},{status:400});const exists=await prisma.habit.findFirst({where:{id,userId:user.id}});if(!exists)return NextResponse.json({error:'NOT_FOUND'},{status:404});const d:any={...parsed.data};if(d.reminderMode==='NONE'){d.reminderTime=null;d.reminderIntervalMinutes=null;d.reminderStartTime=null;d.reminderEndTime=null}else if(d.reminderMode==='FIXED'){d.reminderIntervalMinutes=null;d.reminderStartTime=null;d.reminderEndTime=null}else if(d.reminderMode==='INTERVAL'){d.reminderTime=null}const habit=await prisma.habit.update({where:{id},data:d});return NextResponse.json({habit})}
export async function DELETE(req:NextRequest,ctx:Params){const user=await apiUser(req);if(!user)return NextResponse.json({error:'UNAUTHORIZED'},{status:401});if(!sameOrigin(req))return NextResponse.json({error:'Invalid origin'},{status:403});const {id}=await ctx.params;const result=await prisma.habit.deleteMany({where:{id,userId:user.id}});if(!result.count)return NextResponse.json({error:'NOT_FOUND'},{status:404});return NextResponse.json({ok:true})}
