'use client'
import { BatteryCharging, CheckCircle2, Flame, TimerReset, TrendingUp } from 'lucide-react'
import { useEffect, useState } from 'react'
import { localeFor, useI18n } from '@/lib/i18n'

type Stats={totalTasks:number;completedTasks:number;completionRate:number;focusMinutes:number;focusSessions:number;habitDone:number;habitTarget:number;habitConsistency:number;avgMood:number|null;avgEnergy:number|null;daily:{date:string;total:number;completed:number}[]}
export default function InsightsClient(){
 const {t,lang}=useI18n();const [s,setS]=useState<Stats|null>(null);useEffect(()=>{const load=()=>fetch('/api/stats',{cache:'no-store'}).then(r=>r.json()).then(setS).catch(()=>undefined);void load();const refresh=()=>void load();window.addEventListener('plandan:refresh',refresh);return()=>window.removeEventListener('plandan:refresh',refresh)},[])
 const cards=[{icon:CheckCircle2,value:s?`${s.completionRate}%`:'—',label:t('completionRate')},{icon:TimerReset,value:s?`${Math.floor(s.focusMinutes/60)}h ${s.focusMinutes%60}m`:'—',label:t('focusTime')},{icon:Flame,value:s?`${s.habitConsistency}%`:'—',label:t('habitConsistency')},{icon:BatteryCharging,value:s?.avgEnergy?`${s.avgEnergy}/5`:'—',label:t('energy')}]
 return <><div className="appTop"><div className="pageTitle"><h1>{t('insights')}</h1><p>{t('insightsSubtitle')}</p></div></div><div className="statsGrid">{cards.map(({icon:Icon,value,label})=><div className="card statCard" key={label}><div className="statIcon"><Icon size={18}/></div><div className="statValue">{value}</div><div className="statLabel">{label}</div></div>)}</div><div className="insightGrid"><div className="card cardPad"><div className="cardTitle">{t('weeklyOverview')}</div><div className="small muted" style={{marginTop:4}}>{s?.completedTasks||0} / {s?.totalTasks||0} {t('tasks').toLowerCase()}</div><div className="barList">{(s?.daily||[]).map(row=>{const pct=row.total?Math.round(row.completed/row.total*100):0;const d=new Date(row.date+'T12:00:00');return <div className="barRow" key={row.date}><span>{new Intl.DateTimeFormat(localeFor[lang],{weekday:'short'}).format(d)}</span><div className="barTrack"><div className="barFill" style={{width:`${pct}%`}}/></div><strong>{pct}%</strong></div>})}</div></div><div className="card cardPad"><div className="statIcon"><TrendingUp size={18}/></div><h2 style={{margin:'17px 0 7px',fontSize:22,letterSpacing:'-.035em'}}>{t('rhythmTitle')}</h2><p className="muted" style={{lineHeight:1.65,fontSize:14}}>{t('rhythmSentence').replace('{focus}',String(s?.focusSessions||0)).replace('{habits}',String(s?.habitDone||0))}</p><div className="divider" style={{margin:'18px 0'}}/><div className="small muted">{t('averageMood')}</div><div className="statValue" style={{marginTop:7}}>{s?.avgMood?`${s.avgMood}/5`:'—'}</div></div></div></>
}
